// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-geHIdVlsMSrmkPzdproeo3Bq-vZvOG0',
    appId: '1:833734588024:web:a514d0f3009aeadf8d5f8d',
    messagingSenderId: '833734588024',
    projectId: 'quick-notes-d0841',
    authDomain: 'quick-notes-d0841.firebaseapp.com',
    storageBucket: 'quick-notes-d0841.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ9Yv7R7KItFBZrJnl3QPut2yt5WmUJ1k',
    appId: '1:833734588024:android:f21e3b104c97caad8d5f8d',
    messagingSenderId: '833734588024',
    projectId: 'quick-notes-d0841',
    storageBucket: 'quick-notes-d0841.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyyWZFPAwSTSME-w1DcnjaGE5b7_gIWGQ',
    appId: '1:833734588024:ios:82be5c4e54a038ee8d5f8d',
    messagingSenderId: '833734588024',
    projectId: 'quick-notes-d0841',
    storageBucket: 'quick-notes-d0841.appspot.com',
    iosBundleId: 'com.example.quickNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyyWZFPAwSTSME-w1DcnjaGE5b7_gIWGQ',
    appId: '1:833734588024:ios:82be5c4e54a038ee8d5f8d',
    messagingSenderId: '833734588024',
    projectId: 'quick-notes-d0841',
    storageBucket: 'quick-notes-d0841.appspot.com',
    iosBundleId: 'com.example.quickNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-geHIdVlsMSrmkPzdproeo3Bq-vZvOG0',
    appId: '1:833734588024:web:63f6b5b82101322c8d5f8d',
    messagingSenderId: '833734588024',
    projectId: 'quick-notes-d0841',
    authDomain: 'quick-notes-d0841.firebaseapp.com',
    storageBucket: 'quick-notes-d0841.appspot.com',
  );
}
